.\"/*
.\" * All rights reserved
.\" * Copyright (C) 2016 Andrew Young
.\" * Authors: Andrew Young <andrew@vaelen.org>
.\" *
.\" * This program is free software: you can redistribute it and/or modify
.\" * it under the terms of the GNU General Public License as published by
.\" * the Free Software Foundation, either version 3 of the License, or
.\" * (at your option) any later version.
.\" * 
.\" * This program is distributed in the hope that it will be useful,
.\" * but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" * GNU General Public License for more details.
.\" * 
.\" * You should have received a copy of the GNU General Public License
.\" * along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\" */
.\"
.TH TUNED_PROFILES_MONGODB "7" "10 Aug 2016" "Fedora Power Management SIG" "tuned"
.SH NAME
tuned\-profiles\-mongodb - description of profiles provided for running MongoDB

.SH DESCRIPTION
These profiles are provided for running MongoDB.

.SH PROFILES
The following profiles are provided:

.TP
.BI "mongodb"
Profile optimized for running a MongoDB server.

.SH "FILES"
.NF
.I /usr/lib/tuned/mongodb*

.SH "SEE ALSO"
.BR tuned (8)
.BR tuned\-adm (8)
.BR tuned\-profiles (7)
.SH AUTHOR
.NF
Andrew Young <andrew@vaelen.org>
